"#0" = "The_System_Object"
"#1" = "Root_Class"
"#3" = "Generic_Room"
"#4" = "Generic_Builder"
"#5" = "Generic_Thing"
"#6" = "Generic_Player"
"#7" = "Generic_Exit"
"#8" = "Generic_Container"
"#9" = "Generic_Note"
"#10" = "Login_Commands"
"#11" = "Player_Last_huh_Verbs"
"#12" = "Guest_Log"
"#13" = "Generic_BigList_Utilities"
"#14" = "Generic_Large-Capacity_Mail_Recipient"
"#15" = "Limbo"
"#16" = "Registration_Database"
"#17" = "Player-Creation-Log"
"#18" = "Verb_Help_DB"
"#19" = "Core_Utility_Help"
"#20" = "String_Utilities"
"#21" = "Building_Utilities"
"#22" = "Programmer_Help"
"#24" = "Wizard_Utilities"
"#25" = "Site_DB"
"#26" = "Math_Utilities"
"#27" = "Set_Utilities"
"#29" = "New-Prog-Log"
"#30" = "Generic_Help_Database"
"#31" = "Generic_Guest"
"#32" = "Mr._Spell"
"#33" = "Sequence_Utilities"
"#34" = "Quota-Log"
"#35" = "You"
"#36" = "Hacker"
"#37" = "Generic_Database"
"#38" = "Everyman"
"#39" = "Player_Database"
"#40" = "Generic_Mail_Receiving_Player"
"#41" = "Gender_Utilities"
"#42" = "Permissions_Utilities"
"#43" = "Time_Utilities"
"#45" = "Generic_Mail_Recipient"
"#46" = "Mail_Distribution_Center"
"#47" = "Mail_Room"
"#48" = "Note_Editor"
"#49" = "Verb_Editor"
"#50" = "Generic_Editor"
"#51" = "Matching_Utilities"
"#52" = "Object_Utilities"
"#53" = "Lock_Utilities"
"#54" = "Generic_Letter"
"#55" = "List_Utilities"
"#56" = "Command_Utilities"
"#57" = "Generic_Wizard"
"#58" = "Generic_Programmer"
"#59" = "Code_Utilities"
"#60" = "Help_Database"
"#61" = "News"
"#62" = "The_First_Room"
"#63" = "Recycling_Center"
"#64" = "Telnet_Handler"
"#65" = "Mail_Options"
"#66" = "Edit_Options"
"#68" = "Generic_Option_Package"
"#69" = "Error_Generator"
"#70" = "Site-Locks"
"#71" = "Housekeeper"
"#72" = "Network_Utilities"
"#73" = "Generic_BigList_Resident"
"#74" = "Generic_Feature_Object"
"#75" = "Shapes_Object_Serialization_Library"
"#76" = "Programmer_Options"
"#77" = "Builder_Options"
"#79" = "Byte_Quota_Utilities"
"#80" = "@paranoid_Database"
"#81" = "Object_Quota_Utilities"
"#82" = "Server_Options"
"#83" = "Feature_Warehouse"
"#84" = "Builder_Help_DB"
"#87" = "Password_Verifier"
"#88" = "Frand's_Player_Class"
"#89" = "Stage-Talk_Feature"
"#90" = "Pasting_Feature"
"#91" = "Vector_And_Matrix_Utils"
"#93" = "Conversion_Utils"
"#94" = "Generic_Gendered_Object"
"#95" = "List_Editor"
"#97" = "HTTP_Server"
"#99" = "ANSI_Utilities"
"#100" = "ANSI_PC"
"#101" = "ANSI_Help"
"#102" = "ANSI_Options"
"#103" = "Generic_Message_Dispatch_Object"
"#104" = "Generic_MCP_Package"
"#105" = "mcp-negotiate"
"#106" = "mcp-cord"
"#107" = "MCP_2.1_Parser"
"#108" = "Generic_MCP_2.1_Session"
"#109" = "MCP_Package_Registry"
"#110" = "MCP_2.1"
"#111" = "Object_Prototype"
"#112" = "Generic_Waif"
"#113" = "dns-org-mud-moo-simpleedit"
"#114" = "Integer_Prototype"
"#115" = "List_Prototype"
"#117" = "Map_Prototype"
"#118" = "Generic_Anonymous_Object"
"#119" = "String_Prototype"
"#120" = "Generic_Base_Primitive"
"#121" = "dns-com-vmoo-client"
"#122" = "Generic_Editor_Utilities"
"#123" = "dns-com-awns-status"
"#124" = "Generic_Editing_State_Anon"
"#125" = "Menu_Utilities"
"#127" = "VCS"
